lab1<-expression(paste("AOU", " ", "(" ,mu, "mol", " ", kg^-1,")"))
lab2<-expression(paste(log[10]," ", b[bp]," ", "(700)" , " ", "(" , m^-1, ")"))
lab3<-expression(paste(log[10], " ", "chla", " ", "(" ,"mg", " ", m^-3, ")"))
lab4<-expression(paste(b[bp]," ", "(700)" , " ", "(" , m^-1, ")"))
lab5<-expression(paste("chla", " ", "(" ,"mg", " ", m^-3, ")"))
lab6<-expression(paste("Temperature (",degree~C,")"))
lab7<-("Salinity")
lab8<-expression(paste(Density , " ", "(","kg", " ", m^-3, ")"))
lab9<-expression(paste("Oxygen", " ", "(" ,mu, "mol", " ", kg^-1,")"))
lab10 <- expression(italic("Synechococcus"))